### ISSUE TITLE
Example in the README is out of date

### ISSUE THREAD

**Issue by Xe** [haskell-servant/servant-swagger#10]
```
/home/xena/code/db/ponytones/backend/src/Api/Swagger.hs:23:11:
    Not in scope: ‘infoTitle’
    Perhaps you meant ‘_infoTitle’ (imported from Data.Swagger)
```

**Comment by fizruk** [comment]
@Xe `infoTitle` is a lens and should be exported by `Data.Swagger` (from `swagger2`).
The only reason it might not be in scope is that you're using an old (< 1.0) version of `swagger2`.

I should probably add that to the documentation and `build-deps` though.
