### ISSUE TITLE
[validateEveryToJSON] Qualify type name with its module name?

### ISSUE THREAD

**Issue by ryota-ka** [haskell-servant/servant-swagger#110]
Currently, we utilize the `Show` instance of `TypeRep` in the implementation of `validateEveryToJSON` function.

https://github.com/haskell-servant/servant-swagger/blob/9c0ceb9f5cd00a47e922ba5de4be5ad591d99a0a/src/Servant/Swagger/Internal/Test.hs#L138

However, it is reasonable to define `Request` type and `Response` type for each endpoint. In this way the out will be like this:

```
Response: ...
Response: ...
Response: ...
Request: ...
Response: ...
```

This is really confusing, as we can't tell which module those types are defined in.

The proposed solution here is to qualify the type name with the module in which defines it.

```diff
-show (typeOf (undefined :: a))
+tmodule <> "." <> tname
+  where
+    tyCon = typeRep (typeOf (undefined :: a))
+    tmodule = tyConModule tyCon
+    tname = tyConName tyCon
```

Note: `typeRep (Proxy @a)` can also be used instead of `typeOf (undefined :: a)`

**Comment by phadej** [comment]
It will be very ugly for many other use cases (e.g. if a one returns a `Vector User`). :-1:

**Comment by ryota-ka** [comment]
Sounds reasonable. Closing.

Anyway, are there any work arounds to achieve this?
