### ISSUE TITLE
Support swagger2-2.5

### ISSUE THREAD

**Issue by neurogoo** [haskell-servant/servant-swagger#113]
Is it possible to relax the upper bound of swagger2 as there is a new version? Here is pull request for that https://github.com/haskell-servant/servant-swagger/pull/112 . I have also similar wish for servant-swagger-ui. I can make pull request for that also if this is okay.

**Comment by dmjio** [comment]
@neurogoo, sounds good, feel free to make a PR to `servant-swagger-ui` as well.

**Comment by neurogoo** [comment]
Thanks! Here is the issue and link to the PR in `servant-swagger-ui` https://github.com/haskell-servant/servant-swagger-ui/issues/74

**Comment by charlescrain** [comment]
Looks like this issue has been resolved, correct?

**Comment by phadej** [comment]
@charlescrain indeed it is. Thanks for the note.
