### ISSUE TITLE
add instance of toSchema Swagger + adjust the Todo.hs example to leverage it

### ISSUE THREAD

**Issue by teto** [haskell-servant/servant-swagger#120]
I want to have a route that returns an openspec api :
`type MyAppAPI = HealthcheckAPI  :<|> DocsAPI`

I first tried
`type DocsAPI = "docs" :> "openapi.json" :> Get '[JSON] TS.Text` with a call `toSwagger (Proxy MyAppAPI)` but that would return the full json as an escaped string e.g. `"{\"swagger\": \"2.\" ... }"`

I've then found https://github.com/haskell-servant/servant-swagger/blob/master/example/src/Todo.hs that carefully separates the swagger route from the rest: if you don't you get
`type DocsAPI = "docs" :> "openapi.json" :> Get '[JSON] Swagger`which results in `No instance for (ToSchema Swagger)`
I've added a dummy instance of `toSchema Swagger` to fix it but shouldn't that be part of core ?

**Comment by dmjio** [comment]
It should not be a part of the core. This is equivalent to saying that the openAPI spec contains a route that returns the openAPI spec.

Instead, I would do:

```haskell
swaggerObject = toSwagger (Proxy @ HealthcheckAPI)
```

and then deliver it with `serve`:

```haskell
app :: Application
app = serve (Proxy @ MyAppApi) handlers
  where
     handlers = healthCheckHandlers :<|> pure swaggerObject
```

**Comment by teto** [comment]
ok i see thanks. Still new to this.
