### ISSUE TITLE
HasSwagger instance of UVerb depends on overlappable HasSwagger instance of Verb

### ISSUE THREAD

**Issue by akshaymankar** [haskell-servant/servant-swagger#133]
This is `HasSwagger UVerb ...`
https://github.com/haskell-servant/servant-swagger/blob/1909e44e965dca24cb1f5cee4b08c0781dfdbff6/src/Servant/Swagger/Internal.hs#L192-L204

it depends on overlappable instance `HasSwagger Verb ..` by calling `toSwagger (Proxy :: Proxy (Verb method (StatusOf a) cs a))`. When this instance is actually overriden in a dependant module, the `HasSwagger` instance for `UVerb` doesn't pick that up as it is already compiled and linked with the now overlapped instance. This makes it confusing to write custom instances for a special type.

**Comment by akhesaCaro** [comment]
Hi,
Servant-swagger will be moved into the main Servant repo (see : https://github.com/haskell-servant/servant/pull/1475)
If this issue is still relevant, would it be possible for you to summit it there? : https://github.com/haskell-servant/servant/issues

Thanks in advance!

**Comment by akshaymankar** [comment]
I moved the issue to https://github.com/haskell-servant/servant/issues/1488
