### ISSUE TITLE
blog post draft

### ISSUE THREAD

**Issue by dmjio** [haskell-servant/servant-swagger#16]
cc @jkarni @fizruk 
ANN: Servant-Swagger

Interpreting type-level APIs as value-level APIs.

Servant is not the first project to promote API specifications as first-class citizens, albeit it is the first to promote an API specification as a type. 

Projects like swagger (http://swagger.io/) and apiary (https://apiary.io/) have attempted to formalize the notion of an API specification as a value, specifically, a JSON / YAML object. Servant interpreters like 'servant-client', 'servant-server', 'servant-docs' bridge the gap between type-level specifications and values (i.e. web servers, web clients, and documentation). From the perspective of servant, a swagger/apiary value-level API specification is an object that can be reified from a servant type-level API. This realization has spawned the creation of servant-swagger, an interpreter which creates a swagger.json from a servant API type declaration. 

The swagger 2.0 specification contains not just routes, parameters, headers, and other API information, but also object representations, and validation for their respective fields and types. In order to ensure an accurate interpretation, object metadata from types that exist in a servant type level spec. are accessed using GHC.Generics. Following generic derivation of From/ToJSON instances for types that exist in our servant API we can accurately create json-schema representations that swagger (and its related project swagger-ui) need to display content interactively.

Things to mention
 - [ ] verdict
 - [ ] swagger2
 - [ ] explain swagger more? swagger-ui (most people might not know what it is)

**Comment by jkarni** [comment]
> In order to ensure an accurate interpretation, object metadata from types that exist in a servant type level spec. are accessed using GHC.Generics.

I wouldn't say it's so much about accuracy as it is about convenience.

I think the intro to the blog post can make it clearer how nice `swagger` tooling is. We can have an iframe to a swagger-ui of some API; then talk about code-gen. Then go into the third paragraph. Then build up the code that generates the `swagger.json` for the swagger-ui iframe that we saw.

But these are just thoughts.
