### ISSUE TITLE
Fix http status codes for servant-0.5

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant-swagger#29]
Unfortunately `servant-swagger` compiles with `servant-0.5`, but results in incorrect http status codes in the swagger spec: `Post` generates `200` responses in `servant-server-0.5` but the generated swagger spec still reports `201` (which was true for `servant-server-0.4`.)

**Comment by fizruk** [comment]
AFAIK this is the only inconsistency.

We can fix this temporarily with a CPP, or wait until someone updates Swagger generation for `servant-0.5` (which I was planning on *after* the latter is released).

**Comment by soenkehahn** [comment]
I'd be fine with the latter.

**Comment by JoshuaGross** [comment]
This issue should be resolved with #33

**Comment by soenkehahn** [comment]
Yes, seems like it. Closing.
