### ISSUE TITLE
No default instance for `PostCreated`, other built-in verbs?

### ISSUE THREAD

**Issue by JoshuaGross** [haskell-servant/servant-swagger#32]
Switching over to Servant 0.5 and using `PostCreated` in a route, `toSwagger` now complains: 

```    No instance for (Servant.Swagger.Internal.HasSwagger
                       (Verb 'POST 201 '[CustomResponseType] ResourceType))```

Works fine for `Post`, `Get`, `Delete`, `Post`.

**Comment by JoshuaGross** [comment]
Other things: `Vault` is also not supported. 

I'll keep adding things here if it's helpful, or I can move the discussion over to #30 - I realize now this is all in the scope of "support 0.5"

**Comment by fizruk** [comment]
@JoshuaGross yes, these all should be covered in #30.

I am not sure though when I'd be able to work on this though. PRs are welcome :)
