### ISSUE TITLE
latest version is not reaching stackage lts ?

### ISSUE THREAD

**Issue by simonmichael** [haskell-servant/servant-swagger#37]
New versions of https://www.stackage.org/package/servant-swagger and https://www.stackage.org/package/swagger2 have been in stackage nightlies for weeks, but these have not reached lts-5 for some reason. I'd like to use the newer versions, with stackage lts.

**Comment by JoshuaGross** [comment]
similar issue to #35 - would also appreciate a version bump and pushing this to stackage

**Comment by fizruk** [comment]
@simonmichael I believe Stackage only bumps minor version for every new minor LTS bump. So new versions of `swagger2` and `servant-swagger` would only be available in LTS 6.0 (in a month?). Please correct me if I am wrong!

However you can still use latest versions simply by adding those to `extra-deps` like so:

```yaml
extra-deps:
- swagger2-2.0.2
- servant-swagger-1.0.3
```

@JoshuaGross yes, thank you for reminding about unreleased changes! I will prepare a release now.

**Comment by simonmichael** [comment]
Quite right, that explains it. Thanks.

**Comment by fizruk** [comment]
I am closing this. Feel free to reopen if the problem was not solved.
