### ISSUE TITLE
No instance for (AllCTRender '[] ()) …

### ISSUE THREAD

**Issue by aaronc** [haskell-servant/servant-swagger#43]
I'm getting the following error:

```
No instance for (Servant.API.ContentTypes.AllCTRender '[] ()) …
      arising from a use of ‘serveWithContext’
```

when using API types such as `Post '[] ()` as in the tutorial examples.

I'm able to solve this with:

```
instance AllCTRender '[] () where
  handleAcceptH _ _ _ = Nothing
```

but then I get this warning:

```
Warning: …
    Orphan instance: instance AllCTRender '[] ()
```

Shouldn't this instance already be defined in `Servant.API.ContentTypes`?

**Comment by aaronc** [comment]
Oops, I think I should have opened this in servant, not servant-swagger. Closing here.

**Comment by fizruk** [comment]
Issue in `servant` repo: https://github.com/haskell-servant/servant/issues/498
