### ISSUE TITLE
ToSchema instance for NoContent

### ISSUE THREAD

**Issue by tmbull** [haskell-servant/servant-swagger#47]
Hello, I have an API which uses the `NoContent` types introduced in `servant 0.5`. For example:

```
type DeleteAPI = "widget" :> Capture "id" String :> DeleteNoContent '[JSON] NoContent
```

This results in the following error when `toSwagger` is called:

```
    No instance for (ToSchema Servant.API.ContentTypes.NoContent)
      arising from a use of ‘toSwagger’
```

Naively, I created the the following instance:

```
instance ToSchema NoContent where
  declareNamedSchema _ = pure (NamedSchema Nothing mempty)
```

This satisfies the compile error, but I do not think that this is what we want. The result in swagger.json is something like this:

```
					"204": {
						"schema": {
							"type": "string"
						},
						"description": ""
					}
```

which makes the UI look like:
<img width="234" alt="screen shot 2016-05-26 at 12 54 55 pm" src="https://cloud.githubusercontent.com/assets/8029789/15584639/1e9320c8-2341-11e6-8420-e3c643992e8d.png">

But I think if there is no content in the body, then the response should display in the bottom with the other status codes like this:

<img width="535" alt="screen shot 2016-05-26 at 12 55 42 pm" src="https://cloud.githubusercontent.com/assets/8029789/15584658/32aa0914-2341-11e6-9792-710e0646331c.png">

Based on the swagger docs, I think this can be accomplished by omitting the `schema` node altogether, but I'm not sure if this is even possible without modification to the `swagger2` library. I would be happy to fix this, but I will probably need some direction as I'm not sure what the correct "fix" is at this point. Thanks!

**Comment by fizruk** [comment]
#48 should resolve the issue properly. If possible, please, try it out before I merge.

**Comment by tmbull** [comment]
I commented on the PR as well, but I tested this and it works great. Thanks again for getting to it so quickly!.

**Comment by dmjio** [comment]
@fizruk is quite fast :)

**Comment by fizruk** [comment]
@dmjio except with releases...
