### ISSUE TITLE
JSON schemata are not modified by Aeson's fieldLabelModifier option

### ISSUE THREAD

**Issue by ZjMNZHgG5jMXw** [haskell-servant/servant-swagger#50]
When I use `Aeson`'s `defaultOptions` with a different `fieldLabelModifier`, e.g. `map toUpper`, then the corresponding JSON schemata in the Swagger spec would still show all the field names without the modification induced by `fieldLabelModifier`.

**Comment by fizruk** [comment]
You have to use the same `fieldLabelModifier` for `SchemaOptions` too. E.g.:

```haskell
data Point = Point
  { pointX :: Double
  , pointY :: Double
  } deriving (Generic)

instance ToJSON Point where
  toJSON = genericToJSON defaultOptions { fieldLabelModifier = map toUpper }

instance ToSchema Point where
  declareNamedSchema = genericDeclareNamedSchema defaultSchemaOptions
    { fieldLabelModifier = map toUpper }
```

**Comment by ZjMNZHgG5jMXw** [comment]
Thanks for your instant reply!
Works like charm.

**Comment by fizruk** [comment]
You are welcome!
