### ISSUE TITLE
Fail to define `HasSwagger` instance for custom combinator

### ISSUE THREAD

**Issue by abailly** [haskell-servant/servant-swagger#55]
Hello,
I am trying to generate swagger doc for an API that contains a custom authentication combinator `AuthProtect "foo"` from experimental module in servant. Here is the attempted instance definition:

```
instance (KnownSymbol sym, HasSwagger sub) => HasSwagger (AuthProtect sym :> sub) where
  toSwagger _ = toSwagger (Proxy :: Proxy sub)
```

which is there only to ensure compilation succeeds. But it currently fails with the following unhelpful message:

```
        • Could not deduce (HasSwagger api0)
            arising from a use of ‘toSwagger’
          from the context: (KnownSymbol sym, HasSwagger sub)
            bound by the instance declaration
            at src/Gorilla/Visit/Swagger.hs:59:10-81
          The type variable ‘api0’ is ambiguous
          These potential instances exist:
            20 instances involving out-of-scope types
            (use -fprint-potential-instances to see them all)
        • In the expression: toSwagger (Proxy :: Proxy sub)
          In an equation for ‘toSwagger’:
              toSwagger _ = toSwagger (Proxy :: Proxy sub)
          In the instance declaration for
            ‘HasSwagger (AuthProtect sym :> sub)’
```

What's puzzling me is that `api0` type variable does not seem to appear anywhere in this context...

Thanks for your help.

**Comment by fizruk** [comment]
@abailly did you try `{-# LANGUAGE ScopedTypeVariables #-}` ?

The error message is indeed unhelpful. `api0` most probably refers to `api` in

```haskell
class HasSwagger api where
  toSwagger :: Proxy api -> Swagger
```

If you forgot `ScopedTypeVariables` then `sub` in `toSwagger (Proxy :: Proxy sub)` is just an ambiguous type variable which would be matched against `api`. I guess it's hard for GHC to come up with a helpful error message in this case.

**Comment by abailly** [comment]
Thanks a lot! That seemed to solve the issue. I am a bit ashamed of not having noticed that myself, but usually GHC tells me when I need to set `ScopedTypeVariables` extension... That's somewhat surprising and confusing.

**Comment by ocramz-cc** [comment]
I just ran into this with `servant-swagger-1.1.7.1` and `servant-0.16.2`. Shouldn't the `HasSwagger (AuthProtect` instance be part of this library?
