### ISSUE TITLE
ToJSON instance for NoContent

### ISSUE THREAD

**Issue by noumar** [haskell-servant/servant-swagger#58]
This relates to #47. When defining a JSON API containing `NoContent`, e.g:
```Haskell
type DeleteAPI = "widget" :> Capture "id" String :> DeleteNoContent '[JSON] NoContent
```
it's not possible to run `validateEveryToJSON` on it. This fails with:
```Haskell
No instance for (ToJSON NoContent)
  arising from a use of ‘validateEveryToJSON’
```
How should this be handled?

**Comment by fizruk** [comment]
@noumar a quick fix would be to change `'[JSON]` to, say, `'[PlainText]`. Because it doesn't actually matter for `NoContent` and `validateEveryToJSON` only cares about `JSON`.

I'd say a proper fix should be to change `'[JSON]` to `'[]`. But `servant` does not allow that currently. @jkarni might have an answer why that's the case.

**Comment by noumar** [comment]
Thanks. I can live with `'[PlainText]` for now. But in the long run it would be nice to use `'[JSON]`, so that the entire API is uniformed.

Would it be possible to define some `ToJSON NoContent` and `ToSchema NoContent` instances that "work" and make the tests pass? I could do this e.g. locally in my project.

**Comment by fizruk** [comment]
@noumar yes you totally can define `ToJSON` and `ToSchema` instances (even derive them)!

**Comment by jship** [comment]
These orphan instances worked great for me:

```haskell
instance ToJSON NoContent
instance ToSchema NoContent where
  declareNamedSchema = const $
    pure $ NamedSchema (Just "NoContent") $ mempty
         & type_ .~ SwaggerArray
         & items ?~ SwaggerItemsArray []
         & example ?~ Aeson.Array mempty
instance Arbitrary NoContent where
  arbitrary = pure NoContent
```

**Comment by jonathanjouty** [comment]
Related to #96, even looks like a duplicate actually.
