### ISSUE TITLE
Enumerate all possible Error Codes

### ISSUE THREAD

**Issue by glademiller** [haskell-servant/servant-swagger#59]
I don't think this is possible to do automatically based off of the Servant types (happy to be proven wrong) but it would be nice to have an easy way to control the error status codes, their bodies, descriptions etc for an endpoint. 

It looks like it may be possible to do this today, albeit manually, using the base swagger2 library. If that is the case it would be an easy win to add documentation on how to use it with servant-swagger.

For most of the APIs I build this is a requirement.

**Comment by fizruk** [comment]
It is in fact possible to insert error responses automatically, but you'd have to use custom types to your API. Here's a quick sketch:

```haskell
data ErrorResponse (code :: Nat) (description :: Symbol)

instance
  ( HasSwagger api
  , KnownNat code
  , KnownSymbol description )
  => HasSwagger (ErrorResponse code description :> api) where
  toSwagger _ = toSwagger (Proxy :: Proxy api)
    & setResponse code (return responseSchema)
    where
      code = natVal (Proxy :: Proxy code)
      desc = symbolVal (Proxy :: Proxy description)
      responseSchema = mempty
        & description .~ desc

type MyAPI
  = "resource" :> ResourceId :> ErrorResponse 418 "I'm a teapot" :> Get '[JSON] Resource
```

It is also possible to inject error responses directly into generated `Swagger` spec.
For that you first need to focus on the specific endpoints. Use `Data.Swagger.Operation` or [`subOperations`](http://hackage.haskell.org/package/servant-swagger-1.1.2/docs/Servant-Swagger.html#v:subOperations) for that. For instance:

```haskell
toSwagger (Proxy :: Proxy MyAPI)
  & subOperations (Proxy :: Proxy SubAPI) (Proxy :: Proxy MyAPI)
    %~ setResponse code (return responseSchema)
```

**Comment by glademiller** [comment]
I don't think I ever said thank you for the quick response on this. This is excellent.

**Comment by fizruk** [comment]
@glademiller you're welcome! :)

**Comment by ChShersh** [comment]
@fizruk How can I specify multiple ErrorResponces with Swagger? For example I want to document each API endpoint which error codes it returns and in which cases. For example, for authorization I want to return 404 if such email not found or 401 if password doesn't match email. How could I specify such documentation with `servant` and `servant-swagger`?

**Comment by fizruk** [comment]
@ChShersh I believe the code I provided in https://github.com/haskell-servant/servant-swagger/issues/59#issuecomment-268012934 is still valid.
Does it work for you or do you have something different in mind?

**Comment by neongreen** [comment]
Here's a slightly more recent version with all necessary instances:

```haskell
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE ScopedTypeVariables #-}


import Control.Lens
import GHC.TypeLits
import Servant
import Servant.Swagger
import Data.Swagger
import qualified Data.Text as T


-- Taken from https://github.com/haskell-servant/servant-swagger/issues/59
data ErrorResponse (code :: Nat) (description :: Symbol)

instance
  ( HasSwagger api
  , KnownNat code
  , KnownSymbol desc )
  => HasSwagger (ErrorResponse code desc :> api) where
  toSwagger _ = toSwagger (Proxy :: Proxy api)
    & setResponse (fromInteger code) (return responseSchema)
    where
      code = natVal (Proxy :: Proxy code)
      desc = symbolVal (Proxy :: Proxy desc)
      responseSchema = mempty
        & description .~ T.pack desc

instance HasLink sub => HasLink (ErrorResponse code desc :> sub) where
    type MkLink (ErrorResponse code desc :> sub) = MkLink sub
    toLink _ = toLink (Proxy :: Proxy sub)

instance HasServer api ctx => HasServer (ErrorResponse code desc :> api) ctx where
  type ServerT (ErrorResponse code desc :> api) m = ServerT api m

  route _ = route (Proxy :: Proxy api)
  hoistServerWithContext _ pc nt s = hoistServerWithContext (Proxy :: Proxy api) pc nt s
```

**Comment by neongreen** [comment]
Note: for better results avoid putting `ErrorResponse` after `Capture "xxx"`, because then your error description in Swagger will look like "`xxx` or Error message here`, and not `Error message here` as you want.

**Comment by ChShersh** [comment]
It would be great if this can be included in the library itself instead of copy-pasting and maintaining the same piece of code across different package. I wonder, what stops this code from being included in the library? :thinking: Is it only a partial solution to the problem?
