### ISSUE TITLE
No changelog entry for 1.1.3?

### ISSUE THREAD

**Issue by qrilka** [haskell-servant/servant-swagger#66]
For sure I could check commits but from the other side... :)

**Comment by fizruk** [comment]
@qrilka check and send a PR, please :)

**Comment by fizruk** [comment]
Oh, apparently [there is changelog entry for 1.1.3](https://github.com/haskell-servant/servant-swagger/blob/master/CHANGELOG.md).

**Comment by qrilka** [comment]
Ooops, probably I was checking changelog for 1.1.2.1 :-\

**Comment by phadej** [comment]
Note to self: add a link to github `master` changelog at the top of changelog files, like `aeson` has
