### ISSUE TITLE
Format & type name in QueryParam descriptions?

### ISSUE THREAD

**Issue by michalrus** [haskell-servant/servant-swagger#76]
Hello!

So Swagger-UI has this shortcoming that it won’t display `QueryParam`s’ formats, even though they are present in `swagger.json`.

What we’re doing now is applying this patch to `servant-swagger` (`v1.1.4`) in `default.nix`:

```diff
diff --git a/src/Servant/Swagger/Internal.hs b/src/Servant/Swagger/Internal.hs
index 2576fe0..9abed0b 100644
--- a/src/Servant/Swagger/Internal.hs
+++ b/src/Servant/Swagger/Internal.hs
@@ -30,6 +30,7 @@ import qualified Data.Text as Text
 import GHC.TypeLits
 import Network.HTTP.Media (MediaType)
 import Servant.API
+import Data.Typeable (Typeable, typeRep)
 
 import Servant.Swagger.Internal.TypeLevel.API
 
@@ -246,26 +247,32 @@ instance (KnownSymbol desc, HasSwagger api) => HasSwagger (Summary desc :> api)
     & allOperations.summary %~ (Just (Text.pack (symbolVal (Proxy :: Proxy desc))) <>)
 #endif
 
-instance (KnownSymbol sym, ToParamSchema a, HasSwagger sub) => HasSwagger (QueryParam sym a :> sub) where
+instance (KnownSymbol sym, ToParamSchema a, Typeable a, HasSwagger sub) => HasSwagger (QueryParam sym a :> sub) where
   toSwagger _ = toSwagger (Proxy :: Proxy sub)
     & addParam param
     & addDefaultResponse400 tname
     where
       tname = Text.pack (symbolVal (Proxy :: Proxy sym))
+      pschema = toParamSchema (Proxy :: Proxy a)
+      typeName = show (typeRep (Proxy :: Proxy a))
       param = mempty
         & name .~ tname
+        & description %~ ((Just (Text.pack ("`" ++ typeName ++ "`")) <> ((\f -> " | `" <> f <> "`") <$> pschema ^. format)) <>)
         & schema .~ ParamOther (mempty
             & in_ .~ ParamQuery
-            & paramSchema .~ toParamSchema (Proxy :: Proxy a))
+            & paramSchema .~ pschema)
 
-instance (KnownSymbol sym, ToParamSchema a, HasSwagger sub) => HasSwagger (QueryParams sym a :> sub) where
+instance (KnownSymbol sym, ToParamSchema a, Typeable a, HasSwagger sub) => HasSwagger (QueryParams sym a :> sub) where
   toSwagger _ = toSwagger (Proxy :: Proxy sub)
     & addParam param
     & addDefaultResponse400 tname
     where
       tname = Text.pack (symbolVal (Proxy :: Proxy sym))
+      pschema = toParamSchema (Proxy :: Proxy a)
+      typeName = show (typeRep (Proxy :: Proxy a))
       param = mempty
         & name .~ tname
+        & description %~ ((Just (Text.pack ("`" ++ typeName ++ "`")) <> ((\f -> " | `" <> f <> "`") <$> pschema ^. format)) <>)
         & schema .~ ParamOther (mempty
             & in_ .~ ParamQuery
             & paramSchema .~ (mempty
```

… which results in:

![screenshot-20180216-212719](https://user-images.githubusercontent.com/4366292/36327986-b4253304-1360-11e8-99d3-6a9e6f7fa788.png)

… and now it’s much clearer for consumers what should be sent, when compared to just `string`.

Maybe it would make sense to integrate something like that upstream?…

**Comment by phadej** [comment]
You can get type name for `QueryParam` via

`QueryParam' [Description "some text"] "q" Foo` See picture on https://twitter.com/phadej/status/961962557182562304 :) (We have to add that to the docs somewhere).

Yet I overlooked and you cannot add `Description` to plural `QueryParams`, there isn't primed version. PR to `servant` is welcome.

---

And a question: Doesn't Swagger-UI show a *format* for query arguments anywhere, only a "type" (i.e. plain `string`?) Isn't there a feature request for `swagger-ui` about that, seems like an oversight on their side.

**Comment by michalrus** [comment]
Ohhhh, the new features are very very nice! :heart_eyes_cat: Thank you!

> You can get type name for QueryParam via […]

But, in your example, `QueryParam' [Description "some text"] "q" Foo`, how would I get a `"Foo" :: Text` out of it, without using `Typeable`? I see no `CatName`/`Int`/`Text` strings in the final render in your tweet, that `typeName` in the diff I linked is really `"CatName"` or `"UTCTime"` etc. =)

I’ll try to find an issue in Swagger-UI and add it if there’s none; but they’ve already ignored two of my pretty detailed issues, IIRC. =( Not really nice — but a very nice contrast w/ Haskell’s community. :tada:

**Comment by michalrus** [comment]
Not found any, reported: https://github.com/swagger-api/swagger-ui/issues/4231.

**Comment by phadej** [comment]
@michalrus thanks for reporting an issue upstream.

For typename in Description you can workaround it like in https://github.com/phadej/servant-swagger-ui/pull/42

**Comment by michalrus** [comment]
Oh, nice! =] Thank you.

**Comment by michalrus** [comment]
It’s… kinda resolved, but obviously only for primitive types, so we’re still using that diff above, to get real names of `newtype`s etc.

Thank you!

**Comment by phadej** [comment]
What you mean "for primitive types" ? `QueryParam '[Description "foo"]` works with everything?

**Comment by michalrus** [comment]
Yes, and that’s what we use ±!

I meant that if you don’t add any `Description` manually (which we do automatically based on `Typeable`), then you get only `int`/`string`/etc. with their Swagger-UI fix.
