### ISSUE TITLE
validateEveryToJSON doesn't give error descriptions

### ISSUE THREAD

**Issue by neongreen** [haskell-servant/servant-swagger#81]
`validateToJSON` is supposed to give out helpful error descriptions, but since `validateEveryToJSON` does `(\x -> validateToJSON x == [])` under the hood, it never prints out the output of `validateToJSON` -- only the `x` for which errors were found.

I supposed that changing the `==` to `===` would fix it, but I'm not sure.

**Comment by fizruk** [comment]
Yes, it would be very nice to have it output the actual errors!

It appears that [`===`](http://hackage.haskell.org/package/QuickCheck-2.11.3/docs/Test-QuickCheck.html#v:-61--61--61-) should suit the task. However, you'd have to update [`props`](https://hackage.haskell.org/package/servant-swagger-1.1.5/docs/Servant-Swagger-Internal-Test.html#v:props) (which `validateEveryToJSON` is based on) to accept a `Property`-predicate (not a `Bool`-predicate). This should be straightforward to implement though.

@neongreen are you willing to submit a PR? :)

**Comment by neongreen** [comment]
Sure, expect a PR later today.
