### ISSUE TITLE
Why does 'Capture' insert an unwanted 404?

### ISSUE THREAD

**Issue by neongreen** [haskell-servant/servant-swagger#90]
**tl;dr** I don't understand commit https://github.com/haskell-servant/servant-swagger/commit/ba4b4da7a92ddb5fb3efbf5454d334aa6085d7c5

---

My route looks like this:

```haskell
      Summary "Delete a category"
      :> "category"
      :> Capture "id" (Uid Category)
      :> Delete '[JSON] NoContent
```

For some reason the `Capture` causes the Swagger description of this endpoint to get an extra possible error code:

```json
  "/category/{id}":{
    "delete":{
      "summary":"Delete a category",
      "produces":[
        "application/json;charset=utf-8"
      ],
      "parameters":[
        {
          "format":"Category ID",
          "required":true,
          "in":"path",
          "name":"id",
          "type":"string"
        }
      ],
      "responses":{
        "404":{
          "description":"`id` not found"
        },
        "200":{
          "description":""
        }
      }
    }
  }
```

Why? Under what conditions can this endpoint return 404?

**Comment by neongreen** [comment]
I guess that a possible reason is "if somebody tries `/categories/someid/more/pieces/here`", but it feels like it shouldn't be a property of the endpoint, but a property of the whole tree, so to speak.

**Comment by phadej** [comment]
if capture fails to parse -> 404; i.e. `/category/b0gusId`

**Comment by phadej** [comment]
note to self: `Lenient` Capture won't ever produce 404; but for others we cannot know for sure.

**Comment by neongreen** [comment]
Can I do something to override this behavior (without forking servant) if I want to ensure that invalid parses produce 400 and not 404? I'm fine with having to manually ensure that the routes don't overlap.

**Comment by phadej** [comment]
@neongreen you can create your own `MyCapture` version of `Capture` combinator.

**Comment by neongreen** [comment]
I haven't checked but my gut feeling is that it won't play nice with the rest of the ecosystem (type families matching on `Capture` but not on `MyCapture`). Maybe I'm wrong, though.

**Comment by neongreen** [comment]
I guess that if errors were represented on the type level then I would be able to post-process the API tree to remove unwanted errors when I know that they are impossible 🤔

**Comment by phadej** [comment]
there are very little if any type families matching on `Capture`.

You'll need to implement bunch of class instances, but for most you can forward to the `Capture` implementation.

**Comment by phadej** [comment]
or optionally you can postprocess the `Swagger` value. No need to make things complicated (i.e. type-level magic).

**Comment by phadej** [comment]
I.e. similar to: http://hackage.haskell.org/package/servant-swagger-1.1.6/docs/Servant-Swagger.html#g:3

`servant-swagger` does most of the job; you might need to tweak the end result still.

**Comment by neongreen** [comment]
Postprocessing Swagger seems to be much trickier. In the Servant model I can always stick a custom tag into a `:>` chain without being afraid that it'll break something; with Swagger it's harder to distinguish between "this is a 404 that got inserted automatically" and "this is a 404 that I explicitly asked to be there".

**Comment by neongreen** [comment]
Anyway, I guess defining my own `Capture` is not that bad.

**Comment by arianvp** [comment]
But this isn't true. `servant-server` produces a `400` error when a capture doesn't match. Not a 404!

https://github.com/haskell-servant/servant/blob/master/servant-server/src/Servant/Server/Internal.hs#L177-L186

So I still think this is a bug.

**Comment by arianvp** [comment]
The only place where `servant` produces a `404` is when the `reqPath` doesn't match any documented routes:

https://github.com/haskell-servant/servant/blob/bf766fbc8f549b6d97f76614eca4397562d3c814/servant-server/src/Servant/Server/Internal/Router.hs#L162-L178

Which then shouldn't even show up in the docs, as it only happens when you  call an endpoint that wasn't in the API spec to begin with

**Comment by fizruk** [comment]
> But this isn't true. `servant-server` produces a `400` error when a capture doesn't match. Not a 404!
> 
> https://github.com/haskell-servant/servant/blob/master/servant-server/src/Servant/Server/Internal.hs#L177-L186
> 
> So I still think this is a bug.

Might it have been 404 before? I'm not sure, but I agree that this should be fixed to match current behaviour!

Also a thought: a few exceptions might be applied, for instance capturing `Text` should never fail, so we probably should not add `400` for that.
