### ISSUE TITLE
Exclude NoContent from types tested by 'validateEveryToJSON'

### ISSUE THREAD

**Issue by neongreen** [haskell-servant/servant-swagger#96]
Currently we have:

```haskell
validateEveryToJSON 
    :: forall proxy api. TMap (Every [Typeable, Show, Arbitrary, ToJSON, ToSchema]) 
                              (BodyTypes JSON api) 
    => proxy api
    -> Spec
```

If the API has stuff like `Delete JSON '[NoContent]` in it, you end up having to write a bogus `instance ToJSON NoContent` in order to please `validateEveryToJSON`.

Let's replace `BodyTypes JSON api` with `Remove NoContent (BodyTypes JSON api)`.

**Comment by fizruk** [comment]
@neongreen good point! Actually I didn't realise we had that in our codebase until this issue 😮
Would you be interested in submitting a PR? 😊

**Comment by neongreen** [comment]
Not any time soon, I'm afraid 😔

**Comment by fisx** [comment]
I'm going to grab this.

If anybody wants to join me in this or anything related to servant-swagger, I'm on zurihac all week-end.

**Comment by fizruk** [comment]
@fisx go ahead and thanks for working on this! 😊
