### ISSUE TITLE
Add "OpenAPI" to the package description so it can be more easily found

### ISSUE THREAD

**Issue by jberryman** [haskell-servant/servant-swagger#97]
As I understand it, "OpenAPI" or "OAS" are the more official/current names for the spec. It might be good to add those keywords to the package description. I often search hackage by CTRL-F searching hackage.org/packages/

Thanks for the library!

**Comment by fizruk** [comment]
Great suggestion! Do you want to submit a small PR with package description update? 😊
I think it is worth mentioning the facts that this package is about OpenAPI 2.0 and OpenAPI 3.0 is not  supported (except the parts where it intersects with OpenAPI 2.0).
