### ISSUE TITLE
Support for OpenAPI 3.0

### ISSUE THREAD

**Issue by ezoerner** [haskell-servant/servant-swagger#99]
Support for OpenAPI 3.0.x (current version is 3.0.2).
Surprisingly, I don't see an issue for this yet, seeing as how 3.0.0 has been out since 2017-07-26.

**Comment by phadej** [comment]
There are no library for *OpenAPI 3.0*. If someone makes it happen, then `servant-openapi3` is easy to do. See https://github.com/GetShopTV/swagger2/issues/105

**Comment by cies** [comment]
This seems to come up a lot for openapi3 servant searches. There seems to be some good news:

https://github.com/fieldstrength/servant-openapi/tree/master/openapi

Enjoy.

**Comment by andys8** [comment]
And https://github.com/biocad/servant-openapi3
